version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_agrosoft
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agrosoft_net

  redis:
    image: redis:7-alpine
    container_name: redis_agrosoft
    restart: always
    ports:
      - "6379:6379"
    networks:
      - agrosoft_net

  backend_agrosoft:
    image: advg2005/backend-agrosoft:1.1
    container_name: backend_agrosoft
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    networks:
      - agrosoft_net
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend/AgroSoft_f
      dockerfile: Dockerfile
    image: frontend-agrosoft:1
    container_name: frontend_agrosoft
    restart: always
    environment:
      - VITE_API_URL=/api/
      - VITE_WEBSOCKET_URL=/
    depends_on:
      - backend_agrosoft
    networks:
      - agrosoft_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/app/media
    depends_on:
      - frontend
      - backend_agrosoft
    networks:
      - agrosoft_net

  manual_usuarios:
    image: advg2005/manual-usuario-agrosoft:1.0
    container_name: manual_usuarios_agrosoft
    restart: always
    ports:
      - "4321:4321"
    networks:
      - agrosoft_net

  documentacion_tecnica:
    image: advg2005/documentacion-tecnica-agrosoft:1.0
    container_name: documentacion_tecnica_agrosoft
    restart: always
    ports:
      - "4322:4322"
    networks:
      - agrosoft_net

volumes:
  postgres_data:
  media_data:

networks:
  agrosoft_net:
    driver: bridge
